name: boktor-apps-infra-synth

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: 18
  AWS_REGION: us-east-1

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build nomopomo app
        run: |
          if [ "${{ github.base_ref }}" = "main" ]; then
            npx nx build nomopomo --configuration=production
          else
            npx nx build nomopomo --configuration=development
          fi
        env:
          NODE_ENV: ${{ github.base_ref == 'main' && 'production' || 'development' }}
      - name: CDK Synth
        run: |
          if [ "${{ github.base_ref }}" = "main" ]; then
            npx nx synth nomopomo-infra --configuration=production
          else
            npx nx synth nomopomo-infra --configuration=development
          fi
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ env.AWS_REGION }}
          LAMBDA_BASIC_AUTH_USERNAME: ${{ secrets.LAMBDA_BASIC_AUTH_USERNAME }}
          LAMBDA_BASIC_AUTH_PASSWORD: ${{ secrets.LAMBDA_BASIC_AUTH_PASSWORD }}
