name: boktor-apps-deploy

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  NODE_VERSION: 18
  AWS_REGION: us-east-1
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'main' && 'production' || 'development' }}
    strategy:
      matrix:
        config:
          - app: nomopomo
            base_name: nomopomo
          - app: boktor-portfolio
            base_name: boktor-portfolio
          - app: lio
            base_name: lio
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Clear dependency cache
        run: rm -rf node_modules

      - name: Install dependencies
        run: bun install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create environment file
        run: |
          if [ "${{ env.ENVIRONMENT }}" = "production" ]; then
            BASE_URL="https://georgeboktor.me"
          else
            BASE_URL="https://dev.georgeboktor.me"
          fi
          
          echo "Creating .env.build.${{ env.ENVIRONMENT }} file"
          echo "NX_PUBLIC_WEB_BASE_URL=$BASE_URL" > .env.build.${{ env.ENVIRONMENT }}
          echo "NX_PUBLIC_POSTHOG_HOST=${{ secrets.NX_PUBLIC_POSTHOG_HOST }}" >> .env.build.${{ env.ENVIRONMENT }}
          echo "NX_PUBLIC_POSTHOG_KEY=${{ secrets.NX_PUBLIC_POSTHOG_KEY }}" >> .env.build.${{ env.ENVIRONMENT }}
          
          echo "Environment file created with appropriate base URL: $BASE_URL"

      - name: Build ${{ matrix.config.app }}
        run: bunx nx build ${{ matrix.config.base_name }} --configuration=${{ env.ENVIRONMENT }}
        env:
          NX_PUBLIC_POSTHOG_HOST: ${{secrets.NX_PUBLIC_POSTHOG_HOST}}
          NX_PUBLIC_POSTHOG_KEY: ${{secrets.NX_PUBLIC_POSTHOG_KEY}}
          NODE_ENV: ${{ env.ENVIRONMENT }}

      - name: Deploy infrastructure
        run: bunx nx deploy ${{ matrix.config.base_name }}-infra --configuration=${{ env.ENVIRONMENT }}
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ env.AWS_REGION }}
          LAMBDA_BASIC_AUTH_USERNAME: ${{ secrets.LAMBDA_BASIC_AUTH_USERNAME }}
          LAMBDA_BASIC_AUTH_PASSWORD: ${{ secrets.LAMBDA_BASIC_AUTH_PASSWORD }}